version: '3'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - 5432:5423
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mpidb}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-dev}
    volumes:
      - db-data:/var/lib/postgresql/data:rw:w

volumes:
  db-data:
