name: Docker Build and Push

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
    
      - name: Check AWS CLI version
        run: aws --version

      - name: Authenticate with AWS ECR
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY }}" | aws configure set aws_access_key_id --profile ecr-user
          echo "${{ secrets.AWS_SECRET_ACCESS }}" | aws configure set aws_secret_access_key --profile ecr-user
          aws ecr get-login-password --region eu-west-1 --profile ecr-user | docker login --username AWS --password-stdin 730335240006.dkr.ecr.eu-west-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t poc . --build-arg DATABASE_URL=postgresql://USER:PASSWORD@127.0.0.1:PORT/DATABASE

      - name: Tag Docker image
        run: docker tag poc:latest 730335240006.dkr.ecr.eu-west-1.amazonaws.com/poc:latest

      - name: Push Docker image to AWS ECR
        run: docker push 730335240006.dkr.ecr.eu-west-1.amazonaws.com/poc:latest
