name: Pulumi
on:
  push:
    branches:
      - develop
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
            node-version: 18
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-west-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
      - run: yarn
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: backend/test
          work-dir: apps/struct
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}